    - name: Install Android SDK & Build Tools
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk wget unzip
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        cd $HOME/android-sdk/cmdline-tools/latest
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O tools.zip
        unzip tools.zip
        rm tools.zip
        mv cmdline-tools/* .  # Fix nested folder issue
        rmdir cmdline-tools    # Clean up empty folder
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        echo "export ANDROID_HOME=$ANDROID_HOME" >> $HOME/.bashrc
        echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $HOME/.bashrc
        source $HOME/.bashrc

        # Accept licenses automatically
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

        # Install required SDK components
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;36.0.0-rc5"
